### PR TITLE
Cloakroom fix and little improves

### PR DESCRIPTION
**Pull request by aleexnl**
-> Solved cloakroom problem.
-> Added translation when trash is not aviable.
-> Added spanish language. (credits to @benitoll)

### CODE REVIEW

**Comment by Senlar** [comment]
Where is the cloakroom fix in there? Missing a commit?

**Comment by aleexnl** [comment]
Uops, I'll fix it rn

**Review by haydo1997 — APPROVED** [review]

**Review by tomasalves8 — APPROVED** [review]

**Review by imagreez — APPROVED** [review]

**Review by SpikE-Odets — APPROVED** [review]
Sorry for the delay on getting back to you on this commit.  I have been busy and needed to do a rewrite of the back-end for this script.  This commit will go in with the new rewrite of the back-end

**Comment by SpikE-Odets** [comment]
updating to fix cloak room and adding es.lua

**Pull request merged**
